include:
  - project: 'iopsys/gitlab-ci-pipeline'
    file: '/static-code-analysis.yml'

stages:
    - static_code_analysis
    - unit_test
    - api_test

variables:
  DEBUG: 'TRUE'
  SOURCE_FOLDER: "src"

run_unit_test:
    stage: unit_test
    image: iopsys/code-analysis:0.20
    allow_failure: true
    script:
    - "./gitlab-ci/setup.sh"
    - "./gitlab-ci/unit-test.sh"

    artifacts:
        when: always
        paths:
            - unit-test-coverage.xml
            - timestamp.log

run_api_test:
    stage: api_test
    image: iopsys/code-analysis:0.20
    allow_failure: true
    script:
    - "./gitlab-ci/setup.sh"
    - "./gitlab-ci/functional-api-test.sh"

    artifacts:
        when: always
        reports:
            junit: ./report/tap.xml
        paths:
            - api-test-coverage.xml
            - api-test-memory-report.xml
            - timestamp.log

